### ISSUE TITLE
npm install doesn't work

### ISSUE THREAD

**Issue by zaceno** [turbodom/turbodom#1]
`npm install turbodom` yields a folder `node_modules/turbodom` containing nothing but a `package.json` file.

Installing through: `npm install turbodom/turbodom` (from github repo), creates the `node_modules/turbodom` folder containing only: `package.json`, `LICENSE.md` and `README.md`

In either case `require('turbodom')` can't work

**Comment by jbucaran** [comment]
Published as 0.0.1.
